### PR TITLE
Add basic compatibility (using a generic wood log) for mods without patches

### PR DESCRIPTION
**Pull request by KennethSamael**
I wanted to argue the advantages of having a generic wood log, but I figured it would be better to just show you. This adds simple script that runs on startup, after all the xml patches have done their work, and checks if there are any trees that are still dropping WoodLog. If it finds any, it replaces them with a new type of generic wood log that has no special properties, but can be used for things that you need raw logs for (fuel, building campfires, etc), or turned into mixed lumber.

Ideally, this would almost never be needed, as there would be an xml patch already to add a proper wood type. But realistically, there's always going to be some mod out there you either haven't heard of, or haven't gotten around to adding proper support for yet. In those cases, I think it's infinitely better to have a functional placeholder, both because it's more immersive than trees dropping mixed lumber, and because not having access to wood logs can break the game.

### CODE REVIEW

**Comment by Adventurer13** [comment]
Thank you for showing me what you meant and the reasons why! 

I wonder if it just wouldn't be easier to switch the default functionality within the mod. Currently, mixed lumber replaces vanilla's WoodLog def, so we get the behavior where unpatched trees drop mixed lumber. You raise the valid problems of realism, uses of raw logs, and potential current/future cases. If we change the default to a generic log replacing vanilla's WoodLog, while still keeping mixed lumber a thing, this should address your concerns and essentially do the same thing as your script does. On the one hand, this means any existing mixed lumber will turn into generic wood logs, but it is a simpler solution going forward. I have a patch that would address scenarios, so they still give mixed lumber by default if already present. Let me know what you think of this solution versus using a script. I may have missed some pros and cons to each solution to the same problem.

I think the reason Qwynn never set it up as such was because a generic wood log was in itself unrealistic and competes against existing wood logs for use. I do kind of agree with your reasoning for it, however. Let me think about it some more.

**Comment by KennethSamael** [comment]
I think it's very important to keep mixed lumber as the replacement for the vanilla WoodLog, as it ensures compatibility with other mods that specify WoodLog in their recipes. If you wanted WoodLog to be actual logs, you'd have to ensure no recipe, whether for buildings, workbenches or surgery, still uses WoodLog. Doing this through manual patching is hopeless, and while it might be possible with a more general patch like the one in this PR, it would be more complicated and might even cause some issues if we fail to account for all the different ways other mods might use wood.

> I think the reason Qwynn never set it up as such was because a generic wood log was in itself unrealistic and competes against existing wood logs for use.

It might be unrealistic, but it's only a placeholder. The commonality is set to 0 to avoid random stuffed things using it. I've played with it for a while now, and the only time I've seen anything made out of generic logs is during the tribal start, as it tries to generate a short bow and pila without specifying what they're made of, which makes it throw an error and default to the first def on the list. This happens without this patch too, by the way, it just defaults to birch instead. Could simply move the generic logs further down in the xml, but I think it actually works out pretty well to have a generic wood type as the default (instead of birch) in those few cases where the game isn't set up to pick a random wood type. I suppose traders might stock the logs themselves now that I think about it, but adding `<tradeability>Sellable</tradeability>` should prevent that. Other than that, I don't think there's any cases where the game will randomly pick the generic logs over other logs.

Also, since making this PR, I've learned a bit more about xpath and realized that a relatively simple xml operation could achieve the same thing as the script, similar to the UniFuel patch. I could whip one up if you want.

**Comment by Adventurer13** [comment]
> I think it's very important to keep mixed lumber as the replacement for the vanilla WoodLog, as it ensures compatibility with other mods that specify WoodLog in their recipes. If you wanted WoodLog to be actual logs, you'd have to ensure no recipe, whether for buildings, workbenches or surgery, still uses WoodLog. Doing this through manual patching is hopeless, and while it might be possible with a more general patch like the one in this PR, it would be more complicated and might even cause some issues if we fail to account for all the different ways other mods might use wood.

I already have to do this. The UniMedical patch is an example where I modify recipes use the respective _thingcategories_ for logs (_WoodTypes_) or lumber (_WoodLumber_) instead of WoodLog. However, you do make a good point with WoodLog remaining mixed lumber in the sense that it can still be crafted whereas if it was the generic wood log it might not be obtainable for unpatched mods. I hadn't considered that before, so I definately now agree with you on keeping WoodLog as mixed lumber.

> It might be unrealistic, but it's only a placeholder. The commonality is set to 0 to avoid random stuffed things using it. I've played with it for a while now, and the only time I've seen anything made out of generic logs is during the tribal start, as it tries to generate a short bow and pila without specifying what they're made of, which makes it throw an error and default to the first def on the list. This happens without this patch too, by the way, it just defaults to birch instead. Could simply move the generic logs further down in the xml, but I think it actually works out pretty well to have a generic wood type as the default (instead of birch) in those few cases where the game isn't set up to pick a random wood type.

I believe that is the scenario issue that I mention; I forgot it defaulted to the first def. I'll probably end up organizing it alphabetically by label like it currently is (bamboo being a current exception).

> I suppose traders might stock the logs themselves now that I think about it, but adding `<tradeability>Sellable</tradeability>` should prevent that. Other than that, I don't think there's any cases where the game will randomly pick the generic logs over other logs.

Yeah, I have a few ideas on managing the _TraderKindDefs_ for the generic wood logs.

> Also, since making this PR, I've learned a bit more about xpath and realized that a relatively simple xml operation could achieve the same thing as the script, similar to the UniFuel patch. I could whip one up if you want.

My only concerns would be the game's load order (of Assemblies then Defs then patches Defs) with respect to other mods modifying EW and load times. Primarily load times are my concern. The patch file might work better than or similar to the script. Go ahead and try it! I have an unfortunately growing list of unpatched mods in the **Maybe** section of the [EW Project](https://github.com/Adventurer13/ExpandedWoodworking/projects/1) which it can be tested with.

**Comment by KennethSamael** [comment]
Uploaded the XML patch on a [separate branch](https://github.com/KennethSamael/ExpandedWoodworking/tree/GenericCompatibilityPatchXML). It's almost embarrassing how much simpler it ended up being, all the things I were concerned about just ends out working out without needing to do anything fancy. I tested it with Alpha Biomes, since I noticed there are some inconsistencies within that mod for how the harvestedThingDef is defined. For example, AB_SessileMechanoid works like vanilla trees, using TreeBase as parent and inheriting the harvestedThingDef from there. This works fine, since TreeBase itself gets patched. Note that vanilla trees won't be affected by this, even though they also use the TreeBase, since their own harvestedThingDef takes precedence. On the other hand, there's AB_ArbuscularMycorrhiza, which doesn't use the TreeBase, instead setting harvestThingDef as WoodLog directly. This also works fine, as the patch does what you'd expect, replacing WoodLog with WoodLog_Generic.

With regards to load order and other patches, anything inheriting the harvestedThingDef from TreeBase should always work fine, as this patch won't even touch those trees directly. With trees that define harvestedThingDef as WoodLog directly, load order technically matters; you'd want any other patch affecting it to load before this, so that this patch will simply skip over it. But even if this patch goes first, the other patch would just overwrite it if they set up their xpath correctly.

**Review by Adventurer13 — CHANGES_REQUESTED** [review]
Before I merge this, I need a few changes made.

- Remove the 1.0 support since I am no longer making changes to that version.
- Add your Patch file.

**Comment by KennethSamael** [comment]
Done.

**Review by Adventurer13 — APPROVED** [review]

**Comment by Adventurer13** [comment]
Thank you!

**Pull request merged**
